on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: terraform validate
      #   uses: dflook/terraform-validate@v1

      - name: terraform format
        uses: dflook/terraform-fmt@v1
